export default {
    settings: { name: "V1", slug: "v1", isDefault: true },
    sidebar: [
        {
            type: "section",
            label: "Home",
            visibility: "PUBLIC",
            pages: [
                { type: "page", path: "./4.17.15#chunk.mdx" },
                { type: "page", path: "./4.17.15#compact.mdx" },
                { type: "page", path: "./4.17.15#difference.mdx" },
                { type: "page", path: "./4.17.15#drop.mdx" },
                { type: "page", path: "./4.17.15#dropRight.mdx" },
                { type: "page", path: "./4.17.15#dropRightWhile.mdx" },
                { type: "page", path: "./4.17.15#dropWhile.mdx" },
                { type: "page", path: "./4.17.15#fill.mdx" },
                { type: "page", path: "./4.17.15#findIndex.mdx" },
                { type: "page", path: "./4.17.15#findLastIndex.mdx" },
                { type: "page", path: "./4.17.15#first.mdx" },
                { type: "page", path: "./4.17.15#flatten.mdx" },
                { type: "page", path: "./4.17.15#flattenDeep.mdx" },
                { type: "page", path: "./4.17.15#flattenDepth.mdx" },
                { type: "page", path: "./4.17.15#filter.mdx" },
                { type: "page", path: "./4.17.15#find.mdx" },
                { type: "page", path: "./4.17.15#findLast.mdx" },
                { type: "page", path: "./4.17.15#flatMap.mdx" },
                { type: "page", path: "./4.17.15#flatMapDeep.mdx" },
                { type: "page", path: "./4.17.15#flatMapDepth.mdx" },
                { type: "page", path: "./4.17.15#groupBy.mdx" },
                { type: "page", path: "./4.17.15#initial.mdx" },
                { type: "page", path: "./4.17.15#now.mdx" },
                { type: "page", path: "./4.17.15#size.mdx" },
            ],
        },
    ],
};